ids = [2462881, 2463029, 2463447]
names = ["Laayoune", "Boujdour", "Dakhla"]
ascii_names = [0, 0, 0]    
positions = [[27.1418, -13.18797], [26.13073, -14.48513], [23.68477, -15.95798]]
alternate_names = [["Aaium", "Aaiun", "Aaiún", "Aiun", "Ajuno", "Al Ayoun", "Al-Aaiun", "Al-Ajoen", "Al-Ayun", "Al-Ujun", "EUN", "Ehl'-Ajun", "Ejbei Uad el Aabd", "El Aaiun", "El Aaiún", "El Aium", "El Aiun", "El Aiún", "El Ajun", "El Ayun", "El-Aaiun", "El-Aaiún", "La'Youn", "Laayoune", "Laâyoune", "La’Youn", "O Aiún - العيون", "a you en", "aiun", "el-aiun", "Ел Ајун", "Эль-Аюн", "العيون", "العیون", "アイウン", "阿尤恩", "엘아이운"], ["Boujdour", "Cabo Bojador", "Cape Blanc", "bwjdwr", "بوجدور", "ⴱⵓⵊⴷⵓⵔ"], ["Ad - Dakhla", "Ad Dakhla", "Dajla", "Dakhla", "Dakhlah", "Factoria Villa Cisneros", "VIL", "Villa Cisneras", "Villa Cisneros", "aldakhlt", "dakhlh", "Дахла", "الداخلة", "داخله"]]
timezones = [20, 20, 20]
populations = [196331, 42651, 75000]
altitudes = ["", "", ""]
parents = ["EH", "EH", "EH.CE"]
states = {}
districts = {}
