geoid_list = [3040051, 3041563]
name_list = ["萊塞斯卡爾德－恩戈爾達", "Andorra la Vella"]
ascii_name_list = ["les Escaldes", 0]
alternate_names_list = [["Ehskal'des-Ehndzhordani", "Escaldes", "Escaldes-Engordany", "Les Escaldes", "esukarudesu=engorudani jiao qu", "lai sai si ka er de-en ge er da", "Эскальдес-Энджордани", "エスカルデス＝エンゴルダニ教区", "萊塞斯卡爾德-恩戈爾達", "萊塞斯卡爾德－恩戈爾達"], ["ALV", "Ando-la-Vyey", "Andora", "Andora la Vela", "Andora la Velja", "Andora lja Vehl'ja", "Andoro Malnova", "Andorra", "Andorra Tuan", "Andorra a Vella", "Andorra la Biella", "Andorra la Vella", "Andorra la Vielha", "Andorra-a-Velha", "Andorra-la-Vel'ja", "Andorra-la-Vielye", "Andorre-la-Vieille", "Andò-la-Vyèy", "Andòrra la Vièlha", "an dao er cheng", "andolalabeya", "andwra la fyla", "Ανδόρρα", "Андора ла Веля", "Андора ла Веља", "Андора ля Вэлья", "Андорра-ла-Велья", "אנדורה לה וולה", "أندورا لا فيلا", "አንዶራ ላ ቬላ", "アンドラ・ラ・ヴェリャ", "安道爾城", "안도라라베야"]]
latitude_list = [42.50729, 42.50779]
longitude_list = [1.53414, 1.52109]
country_code_list = ["AD", "AD"]
population_list = [15853, 20430]
dem_list = [1033, 1037]
timezone_list = [266, 266]
altitude_list = [-1, -1]
_feature_class_list = ["P", "P"]
_feature_code_list = ["PPLA", "PPLC"]
_parent_code_list = ["AD.08", "AD.07"]
_states = {"AD.06": ["圣胡利娅-德洛里亚", "Sant Julia de Loria", 3039162], "AD.05": ["奥尔迪诺", "Ordino", 3039676], "AD.04": ["La Massana", "La Massana", 3040131], "AD.03": ["Encamp", "Encamp", 3040684], "AD.02": ["卡尼略", "Canillo", 3041203], "AD.07": ["Andorra la Vella", "Andorra la Vella", 3041566], "AD.08": ["萊塞斯卡爾德-恩戈爾達", "Escaldes-Engordany", 3338529]}
_districts = {}