ids = [2078127]
names = ["飞鱼湾"]
ascii_names = [0]    
positions = [[-10.42172, 105.67912]]
alternate_names = [["Flain-Fish-Kouv", "Flaing Fish Kouv", "Flajing Fish Kouv", "Flajing-Fish-Kouv", "Flayinq Fis Kouv", "Flayinq Fiş Kouv", "Flying Fish Cove", "Kampong", "The Settlement", "fala'iga fisa kova", "fei yu wan", "flay xing fich khof", "flayngh fysh kwf", "flayyng fsh kww", "peullaingpisikobeu", "phla'inga phisa kova", "pilaiyin pis kov", "plaing-pishi", "Флаинг Фиш Коув", "Флайинг-Фиш-Коув", "Флаін-Фіш-Коўв", "Флајинг Фиш Коув", "فلائینگ فش کوو", "فلاينغ فيش كوف", "फ्लाइंग फिश कोव", "ਫ਼ਲਾਇੰਗ ਫ਼ਿਸ਼ ਕੋਵ", "பிளையிங் பிஷ் கோவ்", "ฟลายอิงฟิชโคฟ", "ფლაინგ-ფიში", "フライング・フィッシュ・コーブ", "飞鱼湾", "플라잉피시코브"]]
timezones = [323]
populations = [500]
altitudes = [-1]
parents = ["CX.00"]
states = {}
districts = {}
