ids = [2411585]
names = ["直布罗陀"]
ascii_names = [0]    
positions = [[36.14474, -5.35257]]
alternate_names = [["Calpe", "Cebelitarik", "Cebelitarık", "Djibraltar", "GIB", "Gibbilterra", "Gibilterra", "Gibraltar", "Gibraltaras", "Gibraltaro", "Gibraltár", "Gíbraltar", "Kamaka", "Xibraltar", "Xibraltar - Gibraltar", "gybrltr", "jbl tarq", "jibeulolteo", "jiburarutaru", "mhmyt jbl tarq", "zhi bu luo tuo", "Ĝibraltaro", "Γιβραλτάρ", "Гибралтар", "Ґібралтар", "גיברלטר", "جبل طارق", "جبل‌الطارق", "محمية جبل طارق", "ジブラルタル", "直布罗陀", "지브롤터"]]
timezones = [278]
populations = [26544]
altitudes = [-1]
parents = ["GI.00"]
states = {}
districts = {}
