ids = [3376762, 3377408, 3378644]
names = ["新阿姆斯特丹", "Linden", "乔治敦"]
ascii_names = [0, 0, 0]    
positions = [[6.24793, -57.5171], [6.00809, -58.30714], [6.80448, -58.15527]]
alternate_names = [["N'ju-Amstehrdam", "Naujasis Amsterdamas", "New Amsterdam", "Nueva Amsterdam", "Nueva Ámsterdam", "QSX", "nyuamseuteleudam", "xin a mu si te dan", "Нью-Амстэрдам", "ניו אמסטרדם", "新阿姆斯特丹", "뉴암스테르담"], ["Linden", "Линден"], ["Demerara", "Dzhordzhtaun", "Dzordztaun", "Dzordztauna", "Dzordztaunas", "Dzordztauns", "Džordžtaun", "Džordžtauna", "Džordžtaunas", "Džordžtauns", "GEO", "Georgetown", "Georgetown i Guyana", "Georgiopolis", "Georgurbo", "Gorgtauno", "Jojton", "Jòjtòn", "Tzortztaoun", "Zhorzhtaun", "cxrc thawn", "gwrgtʼwn", "jarajata'una", "jarj ٹawn  gyana", "jarjata'una", "jojitaun", "jorjata'una", "jorjtavun", "jrj‌tawn", "jwrj tawn", "jwrj twghn", "qiao zhi dui", "qiao zhi dun", "zuo zhi cheng", "Ĝorĝtaŭno", "Τζορτζτάουν", "Τζώρτζταουν", "Џорџтаун", "Джорджтаун", "Джорджтаўн", "Жоржтаун", "Ջորջթաուն", "גורגטאון", "جارج ٹاؤن، گیانا", "جرج‌تاون", "جورج تاون", "جورج توغن", "جورج‌تاو", "जॉर्जटाउन", "ਜਾਰਜਟਾਊਨ", "ଜର୍ଜଟାଉନ", "ஜோர்ஜ்டவுண்", "ജോർജ്ജ് ടൗൺ", "จอร์จทาวน์", "ཅོར་ཅི་ཐོན།", "ჯორჯტაუნი", "ጆርጅታውን", "ジョージタウン", "乔治敦", "佐治城", "조지타운"]]
timezones = [103, 103, 103]
populations = [35039, 44690, 235017]
altitudes = ["", "", ""]
parents = ["GY.13", "GY.18", "GY.12"]
states = {"GY.19": ["Upper Takutu-Upper Essequibo", "Upper Takutu-Upper Essequibo", 3375463], "GY.18": ["Upper Demerara-Berbice", "Upper Demerara-Berbice", 3375469], "GY.17": ["Potaro-Siparuni", "Potaro-Siparuni", 3376386], "GY.16": ["Pomeroon-Supenaam", "Pomeroon-Supenaam", 3376407], "GY.15": ["Mahaica-Berbice", "Mahaica-Berbice", 3377274], "GY.14": ["Essequibo Islands-West Demerara", "Essequibo Islands-West Demerara", 3378741], "GY.13": ["East Berbice-Corentyne", "East Berbice-Corentyne", 3378840], "GY.12": ["Demerara-Mahaica", "Demerara-Mahaica", 3378950], "GY.11": ["Cuyuni-Mazaruni", "Cuyuni-Mazaruni", 3379023], "GY.10": ["Barima-Waini", "Barima-Waini", 3379515]}
districts = {}
