geoid_list = [3380387, 3380892, 3380965, 3381303, 3382160]
name_list = ["Saint-Laurent-du-Maroni", "Rémire-Montjoly", "Matoury", "Kourou", "Cayena"]
ascii_name_list = [0, "Remire-Montjoly", 0, 0, 0]
alternate_names_list = [["LDX", "Laurent", "Maroni", "Saint Laurent", "Saint-Laurent-du-Maroni", "Sainte Laurent", "Sen Loran di Maroni", "Sen Loren du Maroni", "Sen-Loran-dju-Maroni", "ma luo ni he pan sheng luo lang", "san lwran dw marwny", "san=roran=deyu=maroni", "sn lwran dw mrwny", "Сен Лоран ди Марони", "Сен-Лоран-дю-Марони", "Сен-Лоран-дю-Мароні", "سان لوران دو ماروني", "سن لوران دو مرونی", "سینٹ-لارنٹ-دو-مارونی", "サン＝ローラン＝デュ＝マロニ", "马罗尼河畔圣洛朗"], ["Montjoli"], ["Matoary", "Matoury"], ["Bourg de Kourou", "Kouro", "Kourou", "Kur", "Kuru", "QKR", "ku lu", "kuru", "kwrwa", "Кур", "Куру", "كوروا", "クールー", "库鲁"], ["CAY", "Caiena", "Caienna", "Cajen-a", "Cajena", "Cayena", "Cayene", "Cayenne", "Kaena", "Kaenna", "Kagien", "Kajen", "Kajena", "Kajenna", "Kajennae", "Kajenneh", "Kajeno", "Kayen", "Kayene", "Kayenna", "kai yun", "kaien'nu", "kaiyana", "kayen", "kayena", "kayn", "kayyn", "Καγιέν", "Каена", "Кайен", "Кайеннæ", "Кайенна", "Кайеннэ", "Каєнна", "Кајена", "Կայեննա", "קאיין", "كايين", "کائین", "کاین", "कायेन", "ਕੈਯਨ", "கயேன்", "กาแยน", "კაიენა", "カイエンヌ", "開雲", "카옌"]]
latitude_list = [5.50153, 4.91667, 4.84921, 5.16281, 4.93333]
longitude_list = [-54.02916, -52.26667, -52.32355, -52.64265, -52.33333]
country_code_list = ["GF", "GF", "GF", "GF", "GF"]
population_list = [24287, 19029, 26350, 24029, 61550]
dem_list = [10, 7, 13, 7, 7]
timezone_list = [81, 81, 81, 81, 81]
altitude_list = [-1, -1, -1, -1, -1]
_feature_class_list = ["P", "P", "P", "P", "P"]
_feature_code_list = ["PPLA2", "PPL", "PPLA3", "PPLA3", "PPLC"]
_parent_code_list = ["GF.GF.973", "GF.GF.973", "GF.GF.973", "GF.GF.973", "GF.GF.973"]
_states = {"GF.GF": ["Guayana Francesa", "Guyane", 6690605]}
_districts = {"GF.GF.973": ["Guyane", "Guyane", 6690606]}