ids = [3513563]
names = ["Кралендейк"]
ascii_names = ["Kralendijk"]    
positions = [["12.15", "-68.26667"]]
alternate_names = [["Kralendajk", "Kralendehjk", "Kralendeikas", "Kralendejk", "Kralendijk", "Kralendiyk", "Kralentik", "Playa", "ke la lun dai ke", "keulallendeikeu", "kralndyk", "kralyndayk", "kurarendaiku", "Κράλεντικ", "Кралендайк", "Кралендајк", "Кралендейк", "Кралендэйк", "Կրալենդիյկ", "كراليندايك", "کرالندیک", "کرالن‌دیک", "კრალენდეიკი", "クラレンダイク", "克拉伦代克", "크랄렌데이크"]]
timezones = [112]
populations = [3081]
altitudes = [-1]
parents = ["BQ.BO"]
states = {"BQ.BO": ["Bonaire", "Bonaire", 7609816], "BQ.SB": ["Saba", "Saba", 7610358], "BQ.SE": ["Синт-Эстатиус", "Sint Eustatius", 7610359]}
districts = {}
