ids = [6691831]
names = ["Vatican City"]
ascii_names = ["Vatican City"]    
positions = [["41.90268", "12.45414"]]
alternate_names = [["Citta del Vaticano", "Città del Vaticano", "Ciudad del Vaticano", "Etat de la Cite du Vatican", "Staat Vatikanstadt", "Staat der Vatikanstadt", "Vatican", "Vatican City", "Vatican City State", "Vaticano", "Vatikan", "Vatikanas", "Vatikanstaden", "Vatikanstadt", "batikan", "batikan si", "État de la Cité du Vatican", "Ватикан", "바티칸", "바티칸 시"]]
timezones = [315]
populations = [829]
altitudes = [55]
parents = ["VA"]
states = {}
districts = {}
