ids = [3579132]
names = ["Густавия"]
ascii_names = [0]    
positions = [[17.89618, -62.84978]]
alternate_names = [["Goustavia", "Gustaf", "Gustavi", "Gustavia", "Gustavija", "Gustavio", "Gustávia", "Guthavia", "Qustaviya", "guseutabia", "gustavhiya", "gusutabia", "gwiseutabia", "gwstawya", "ju si ta wei ya", "ku s ta wi ya", "kucutaviya", "Γουσταβία", "Густави", "Густавия", "Густавија", "Густавія", "گوستاویا", "گوسٹاویا", "गुस्ताव्हिया", "குசுதாவியா", "กุสตาวียา", "გუსტავია", "グスタビア", "居斯塔维亚", "구스타비아", "귀스타비아"]]
timezones = [151]
populations = [5988]
altitudes = [-1]
parents = ["BL.00"]
states = {}
districts = {}
