ids = [3513392]
names = ["Филипсбург"]
ascii_names = [0]    
positions = [[18.026, -63.04582]]
alternate_names = [["Filip'smpournk", "Filipsburg", "Filipsburgas", "Great Bay", "Philipsburg", "fei li pu si bao", "fi lipsburkh", "firippusuburufu", "flpsbrg", "fylypsbwrg  synt martn", "pilipcuparku", "pillibseubwileuheu", "Φίλιπσμπουργκ", "Филипсбург", "Філіпсбург", "فلپسبرگ", "فیلیپسبورگ، سینت مارتن", "பிலிப்சுபர்கு", "ฟีลิปส์บืร์ค", "ფილიპსბურგი", "フィリップスブルフ", "菲利普斯堡", "필립스뷔르흐"]]
timezones = [116]
populations = [1400]
altitudes = [-1]
parents = ["SX"]
states = {}
districts = {}
