ids = [3513090]
names = ["Willemstad"]
ascii_names = ["Willemstad"]    
positions = [["12.12246", "-68.88641"]]
alternate_names = [["Vilemstad", "Vilemstadas", "Vilemstade", "Vilemstado", "Villemstad", "Villemstant", "Villemştad", "Willemstad", "Willemsted", "Willemstêd", "billemseutateu", "uiremusutatto", "vilemastada", "villemstatu", "wei lian si ta de", "willems tad", "wylmstad", "Βίλλεμσταντ", "Вилемстад", "Виллемстад", "Вілемстад", "Віллемстад", "וילמסטאד", "ويلمستاد", "ویلمستاد", "ویلمسٹیڈ", "विलेमश्टाड", "வில்லெம்ஸ்டாடு", "วิลเลมสตัด", "ვილემსტადი", "ウィレムスタット", "威廉斯塔德", "빌렘스타트"]]
timezones = [88]
populations = [125000]
altitudes = [-1]
parents = ["CW"]
states = {}
districts = {}
