ids = []
names = []
ascii_names = []    
positions = []
alternate_names = []
timezones = []
populations = []
altitudes = []
parents = []
states = {"TK.N": ["Нукунону", "Nukunonu", 4031091], "TK.F": ["Fakaofo", "Fakaofo", 4031112], "TK.A": ["Atafu", "Atafu", 4031116]}
districts = {}
